import { ICandidate, IJob } from '../shared/interfaces/screening.interface';

export const candidates: ICandidate[] = [
    {
        name: "John Doe",
        phone: 1234567890,
        email: "john.doe@example.com",
        candidateId: 1,
        jobId: "job1",
        screeningId: "screening1",
    },
    {
        name: "Jane Smith",
        phone: 9876543210,
        email: "jane.smith@example.com",
        candidateId: 2,
        jobId: "job1",
        screeningId: "screening2",
    },
    {
        name: "Alice Johnson",
        phone: 5555555555,
        email: "alice.johnson@example.com",
        candidateId: 3,
        jobId: "job1",
        screeningId: "screening3",
    },
    {
        name: "Bob Brown",
        phone: 1112223333,
        email: "bob.brown@example.com",
        candidateId: 4,
        jobId: "job1",
        screeningId: "screening4",
    },
    {
        name: "Eva White",
        phone: 9998887777,
        email: "eva.white@example.com",
        candidateId: 5,
        jobId: "job1",
        screeningId: "screening5",
    },
    {
        name: "Sam Wilson",
        phone: 7776665555,
        email: "sam.wilson@example.com",
        candidateId: 6,
        jobId: "job1",
        screeningId: "screening6",
    },
    {
        name: "Olivia Green",
        phone: 4443332222,
        email: "olivia.green@example.com",
        candidateId: 7,
        jobId: "job1",
        screeningId: "screening7",
    },
    {
        name: "William Davis",
        phone: 2221110000,
        email: "william.davis@example.com",
        candidateId: 8,
        jobId: "job1",
        screeningId: "screening8",
    },
    {
        name: "Sophia Black",
        phone: 8887776666,
        email: "sophia.black@example.com",
        candidateId: 9,
        jobId: "job1",
        screeningId: "screening9",
    },
    {
        name: "Liam Gray",
        phone: 5554443333,
        email: "liam.gray@example.com",
        candidateId: 10,
        jobId: "job1",
        screeningId: "screening10",
    },
    {
        name: "Ava Brown",
        phone: 6667778888,
        email: "ava.brown@example.com",
        candidateId: 11,
        jobId: "job1",
        screeningId: "screening11",
    },
    {
        name: "Mia White",
        phone: 3332221111,
        email: "mia.white@example.com",
        candidateId: 12,
        jobId: "job1",
        screeningId: "screening12",
    },
    {
        name: "Noah Black",
        phone: 9990001111,
        email: "noah.black@example.com",
        candidateId: 13,
        jobId: "job1",
        screeningId: "screening13",
    },
    {
        name: "Emma Johnson",
        phone: 1110009999,
        email: "emma.johnson@example.com",
        candidateId: 14,
        jobId: "job1",
        screeningId: "screening14",
    },
    {
        name: "James White",
        phone: 2223334444,
        email: "james.white@example.com",
        candidateId: 15,
        jobId: "job1",
        screeningId: "screening15",
    },
    {
        name: "Charlotte Davis",
        phone: 5556667777,
        email: "charlotte.davis@example.com",
        candidateId: 16,
        jobId: "job1",
        screeningId: "screening16",
    },
    {
        name: "Benjamin Smith",
        phone: 7778889999,
        email: "benjamin.smith@example.com",
        candidateId: 17,
        jobId: "job1",
        screeningId: "screening17",
    },
    {
        name: "Luna Taylor",
        phone: 4445556666,
        email: "luna.taylor@example.com",
        candidateId: 18,
        jobId: "job1",
        screeningId: "screening18",
    },
    {
        name: "Henry Martin",
        phone: 8889990000,
        email: "henry.martin@example.com",
        candidateId: 19,
        jobId: "job1",
        screeningId: "screening19",
    },
    {
        name: "Avery Wilson",
        phone: 6665554444,
        email: "avery.wilson@example.com",
        candidateId: 20,
        jobId: "job1",
        screeningId: "screening20",
    },
];

export const jobs: IJob[] = [
    {
        jobId: "job1",
        title: "Senior Java developer"
    },
    {
        jobId: "job2",
        title: "Senior Angular developer"
    }
];
